// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'brightness-filter'
  | 'contrast-filter'
  | 'grayscale-filter'
  | 'hue-rotate-filter'
  | 'invert-filter'
  | 'saturate-filter'
  | 'sepia-filter';
